//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class archive
    {
        public int detailsIdA { get; set; }
        public string userId { get; set; }
        public double temp1A { get; set; }
        public double temp2A { get; set; }
        public double humiditiA { get; set; }
        public double luminosityA { get; set; }
        public double pressureA { get; set; }
        public double altitudeA { get; set; }
        public string timeperiodA { get; set; }
    }
}
