//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class details
    {
        public int detailsId { get; set; }
        public string userId { get; set; }
        public double temperature1 { get; set; }
        public double temperature2 { get; set; }
        public double humidity { get; set; }
        public double luminosity { get; set; }
        public double pressure { get; set; }
        public double altitude { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
